name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  api:
    uses: ./.github/workflows/_docker-build.yml
    with:
      image: ghcr.io/${{ github.repository_owner }}/nestjs-foundation
      target: api
      push: false
      build-args: |
        "appName=nestjs-foundation"
        "nodeVersion=20.17.0"
    secrets: inherit
